# Generated by Django 4.2.11 on 2024-03-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
