# Generated by Django 4.2.11 on 2024-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_labels_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='fat',
            field=models.FloatField(max_length=50),
        ),
    ]
