# Generated by Django 4.2.11 on 2024-03-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_alter_label_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='label',
            name='categories',
            field=models.CharField(choices=[('TINNED FOODS', 'TINNED FOODS'), ('INSTANT STAPLES', 'INSTANT STAPLES'), ('DAIRY & CREAMERS', 'DAIRY & CREAMERS'), ('OILS', 'OILS'), ('BISCUITS', 'BISCUITS'), ('BEVERAGES', 'BEVERAGES'), ('SPREADS, DRESSINGS & SAUCES', ' SPREADS, DRESSINGS & SAUCES'), ('GRAINS & CEREALS', 'GRAINS & CEREALS'), ('PASTA', 'PASTA'), ('INFANT FORMULAE', 'INFANT FORMULAE'), ('NUTRITION SUPPLEMENTS', 'NUTRITION SUPPLEMENTS'), ('SPICES', 'SPICES')], max_length=100),
        ),
        migrations.AddField(
            model_name='label',
            name='net_weight_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net_weight_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='per_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='per_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='serving_quantity_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_quantity_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='serving_size_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_size_unit', to='labels.unit'),
        ),
    ]
