# Generated by Django 4.2.11 on 2024-03-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_unit_alter_label_categories_label_net_weight_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='alcoholc',
            new_name='alcohol',
        ),
        migrations.AddField(
            model_name='label',
            name='L_carnitine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='L_carnitine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='MUFA_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MUFA_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='PUFA_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PUFA_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='added_sugar_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_sugar_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='alanine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alanine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='alcohol_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alcohol_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='apha_linolenic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apha_linolenic_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='arginine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arginine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='ash_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ash_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='aspartic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspartic_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='caffeine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caffeine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='calcium_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calcium_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='carbohydrate_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbohydrate_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='carotenes_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carotenes_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='casein_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casein_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='chloride_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chloride_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='cholesterol_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cholesterol_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='cholin_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cholin_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='chromium_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chromium_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='copper_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copper_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='cystine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cystine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='dietary_fiber_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietary_fiber_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='energy_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='fat_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fat_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='flouride_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flouride_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='glutamic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glutamic_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='glycine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glycine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='histidine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histidine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='inositol_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inositol_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='iodine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iodine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='iron_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iron_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='isoleucine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isoleucine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='leucine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leucine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='linolenic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linolenic_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='lutein_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lutein_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='manganese_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manganese_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='maxagnesium_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maxagnesium_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='methionine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methionine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='moisture_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moisture_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='molybdenum_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molybdenum_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='nucleotides_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleotides_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='omega_3_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omega_3_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='omega_6_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omega_6_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='omega_9_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omega_9_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='phenylalanine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenylalanine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='phosphorus_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phosphorus_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='potassium_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potassium_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='proline_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proline_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='protein_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='salt_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salt_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='saturated_fat_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturated_fat_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='selenium_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selenium_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='serine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='sodium_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sodium_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='sphingomyelin_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sphingomyelin_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='sugar_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugar_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='taurine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taurine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='theobromine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theobromine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='threonine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threonine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='trans_fat_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_fat_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='tryptophan_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tryptophan_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='tyrosine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyrosine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='unsaturated_fat_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsaturated_fat_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='valine_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valine_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_A_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_A_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B12_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B12_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B1_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B1_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B2_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B2_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B3_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B3_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B5_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B5_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B6_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B6_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B7_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B7_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_B9_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_B9_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_C_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_C_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_D_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_D_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_E_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_E_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='vitamin_K_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitamin_K_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='whey_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whey_unit', to='labels.unit'),
        ),
        migrations.AddField(
            model_name='label',
            name='zinc_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zinc_unit', to='labels.unit'),
        ),
    ]
