# Generated by Django 4.2.11 on 2024-03-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0007_rename_alcoholc_label_alcohol_label_l_carnitine_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('TINNED FOODS', 'TINNED FOODS'), ('INSTANT STAPLES', 'INSTANT STAPLES'), ('DAIRY & CREAMERS', 'DAIRY & CREAMERS'), ('OILS', 'OILS'), ('BISCUITS', 'BISCUITS'), ('BEVERAGES', 'BEVERAGES'), ('SPREADS, DRESSINGS & SAUCES', ' SPREADS, DRESSINGS & SAUCES'), ('GRAINS & CEREALS', 'GRAINS & CEREALS'), ('PASTA', 'PASTA'), ('INFANT FORMULAE', 'INFANT FORMULAE'), ('NUTRITION SUPPLEMENTS', 'NUTRITION SUPPLEMENTS'), ('SPICES', 'SPICES')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='categories',
        ),
        migrations.AddField(
            model_name='label',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.category'),
        ),
        migrations.AlterField(
            model_name='label',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.brand'),
        ),
    ]
