# Generated by Django 4.2.11 on 2024-05-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('ANIMAL PROTEINS', 'ANIMAL PROTEINS '), ('SOUP AND STEWS', 'SOUP AND STEWS'), ('PORRIDGES', 'PORRIDGES'), ('LOCAL STAPLES', 'LOCAL STAPLES'), ('FRUITS AND VEGETABLES', 'FRUITS AND VEGETABLES'), ('NUTS AND LEGUMES', 'NUTS AND LEGUMES')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('net_weight', models.FloatField(blank=True, max_length=50, null=True)),
                ('serving_size', models.FloatField(blank=True, max_length=50, null=True)),
                ('serving_quantity', models.FloatField(blank=True, max_length=50, null=True)),
                ('per', models.FloatField(blank=True, max_length=50, null=True)),
                ('energy', models.FloatField(blank=True, max_length=50, null=True)),
                ('carbohydrate', models.FloatField(blank=True, max_length=50, null=True)),
                ('protein', models.FloatField(blank=True, max_length=50, null=True)),
                ('fat', models.FloatField(blank=True, max_length=50, null=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locals.category')),
                ('carbohydrate_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbohydrate_unit', to='Locals.unit')),
                ('energy_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_unit', to='Locals.unit')),
                ('fat_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fat_unit', to='Locals.unit')),
                ('net_weight_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net_weight_unit', to='Locals.unit')),
                ('per_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='per_unit', to='Locals.unit')),
                ('protein_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_unit', to='Locals.unit')),
                ('serving_quantity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_quantity_unit', to='Locals.unit')),
                ('serving_size_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_size_unit', to='Locals.unit')),
            ],
        ),
    ]
