# Generated by Django 4.2.11 on 2024-05-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='Category',
        ),
        migrations.AddField(
            model_name='label',
            name='categories',
            field=models.CharField(blank=True, choices=[('TINNED FOODS', 'TINNED FOODS'), ('INSTANT STAPLES', 'INSTANT STAPLES'), ('DAIRY & CREAMERS', 'DAIRY & CREAMERS'), ('OILS', 'OILS'), ('BISCUITS', 'BISCUITS'), ('BEVERAGES', 'BEVERAGES'), ('SPREADS, DRESSINGS & SAUCES', ' SPREADS, DRESSINGS & SAUCES'), ('GRAINS & CEREALS', 'GRAINS & CEREALS'), ('PASTA', 'PASTA'), ('INFANT FORMULAE', 'INFANT FORMULAE'), ('NUTRITION SUPPLEMENTS', 'NUTRITION SUPPLEMENTS'), ('SPICES', 'SPICES')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
