# Generated by Django 4.2.11 on 2024-05-09 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0006_label_nutrient_label_parent_label_unit_label_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='nutrient',
        ),
        migrations.RemoveField(
            model_name='label',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='label',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='label',
            name='value',
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, max_length=50, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercials.label')),
                ('nutrient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercials.nutrientlist')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercials.unit')),
            ],
        ),
    ]
